### ISSUE TITLE
no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by jcjview** [zhijs/-Reinforcement-Learning-five-in-a-row-#1]
I run it on linux ubuntu ,no display.

Traceback (most recent call last):
  File "run_this.py", line 86, in <module>
    myview =view()
  File "/home/ubuntu/cluster/Reinforcement-Learning-five-in-a-row-/view.py", line 18, in __init__
    super(view, self).__init__()
  File "/home/ubuntu/anaconda3/envs/tensorflow/lib/python3.5/tkinter/__init__.py", line 1876, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by zhijs** [comment]
You need to run an X server on your windows machine and then enable X11 forwarding in your putty session before you log in (see the Connection / SSH / X11 property page in PuTTY).

**Comment by zhijs** [comment]
You need to run an X server on your windows machine and then enable X11 forwarding in your putty session before you log in (see the Connection / SSH / X11 property page in PuTTY).
